'use strict';

module.exports = [
  { name  : 'acrylite-to-air',        jira: 39 },
  { name  : 'ball-drop-1',            jira: 40 },
  { name  : 'car-stop',               jira: 41 },
  { name  : 'car-zoom',               jira: 42 },
  { name  : 'colliding-carts-1',      jira: 43 },
  { name  : 'colliding-carts-2',      jira: 43 },
  { name  : 'colliding-carts-3',      jira: 43 },
  { name  : 'colliding-carts-4',      jira: 43 },
  { name  : 'colliding-carts-5',      jira: 43 },
  { name  : 'colliding-carts-6',      jira: 43 },
  { name  : 'coulomb',                jira: 44 },
  { name  : 'snowboard-run',          jira: 45 },
  { name  : 'snowboard-jump',         jira: 51 },
  { name  : 'snowboard-jump-energy',  jira: 52 },
  { name  : 'snowboard-jump-dynamic', jira: 52 },
  { name  : 'ice-slide-1',            jira: 46 },
  { name  : 'ice-slide-2',            jira: 46 },
  { name  : 'ice-slide-1-model',      jira: 47 },
  { name  : 'ice-slide-2-model',      jira: 47 },
  { name  : 'mass-and-spring',        jira: 48 },
  { name  : 'ripple-tank-doppler',    jira: 49 },
  { name  : 'ripple-tank-waves',      jira: 49 },
  { name  : 'ball-drop-2',            jira: 50 },
  { name  : 'ball-drop-large',        jira: 50 },
  { name  : 'car-round-trip',         jira: 50 },
  { name  : 'spring-wars',            jira: 53 },
  { name  : 'start-up',               jira: 54 },
  { name  : 'start-up-power',         jira: 54 },
  { name  : 'start-up-energy',        jira: 55 },
  { name  : 'swing',                  jira: 56 },
  { name  : 'tennis-ball-bounce',     jira: 57 },
  { name  : 'which-ball-lands-first', jira: 58 },
  { name  : 'air-to-acrylite',        jira: 151 },
  { name  : 'howitzer-cart',          jira: 152 }
];